### ISSUE TITLE
Regarding secret 

### ISSUE THREAD

**Issue by joshisimt** [dasniko/keycloak-springboot-demo#2]
I am trying to access localhost:8080 my application.
it redirects me to keycloak login page but after providing the credentials I got {"error":"unauthorized_client","error_description":"Client secret not provided in request"}

How to pass secret in request ?

Thanks

**Comment by dasniko** [comment]
Please read the Keycloak documentation for proper configuration: http://www.keycloak.org/docs/3.3/securing_apps/topics/oidc/java/java-adapter-config.html#_java_adapter_config
