### ISSUE TITLE
Spring boot and keycloak

### ISSUE THREAD

**Issue by crcpucminas** [dasniko/keycloak-springboot-demo#3]
I'm a beginner in spring security and I need help to make my spring boot applications safer.

I created two simple examples using spring boot:

API (to be secured): https://github.com/crcpucminas/api-service
An API Client (which must access the api): https://github.com/crcpucminas/api-client
I would like to use keycloack (OAuth 2.0) to protect the API and grant access to API Client.

So, I need guidance to:

Configure keycloack (realm, hole, user, etc.);
Set the API configuration (application.properties); and
Set the API Client configuration (application.properties, configuration classes, etc.).
Any help would be appreciated.

Thank you very much.

**Comment by dasniko** [comment]
Crossposting to my blog and my GitHub repo doesn't make it better.
RTFM! http://www.keycloak.org/documentation.html
