### ISSUE TITLE
Compilation Error after checked out this project into eclipse[Version: 2022-06 (4.24.0)].

### ISSUE THREAD

**Issue by billson-my** [dasniko/keycloak-springboot-demo#4]
/keycloak-springboot-demo/src/main/java/dasniko/customer/CrmController.java

JDK: 1.8u265

Please highlight if any steps are required after check out from git.

![image](https://user-images.githubusercontent.com/10073838/181162228-76b5bee5-41e6-4bfc-b5df-0bdd55aadf6e.png)

![image](https://user-images.githubusercontent.com/10073838/181164693-43291130-e738-4ab5-948d-171d2e491643.png)

**Comment by dasniko** [comment]
This is an old and outdated project, it's not maintained and the way doing things here is no more supported as the Keycloak Spring adapter is deprecated. Don't use it!
